export type Recette = {
  id: string;
  nom: string;
  description: string;
  tempsPreparation: number;
  coutPreparation: number;
  prixVente: number;
  categorie:
    | 'Entrée'
    | 'Plat'
    | 'Dessert'
    | 'Charcuterie'
    | 'International'
    | 'Traditionnel'
    | 'Grillade'
    | 'Produit'
    | 'Soupe'
    | 'Divers';
  actif: boolean;
};

const recettesExemple: Recette[] = [
  // === 🐔 POULETS ET DÉCOUPES ===
  {
    id: '1',
    nom: 'Poulet entier standard',
    description: 'Poulet de chair abattu à 35-45 jours, vendu entier ou découpé (ailes, cuisses, filets).',
    tempsPreparation: 40,
    coutPreparation: 21000,
    prixVente: 24000,
    categorie: 'Plat',
    actif: true,
  },
  {
    id: '2',
    nom: 'Poulet fermier rôti',
    description: 'Poulet fermier rôti lentement au four avec herbes de Provence et citron.',
    tempsPreparation: 80,
    coutPreparation: 25000,
    prixVente: 35000,
    categorie: 'Traditionnel',
    actif: true,
  },
  {
    id: '3',
    nom: 'Cuisses de poulet grillées',
    description: 'Morceaux marinés au citron et ail, grillés au charbon.',
    tempsPreparation: 45,
    coutPreparation: 18000,
    prixVente: 26000,
    categorie: 'Grillade',
    actif: true,
  },
  {
    id: '4',
    nom: 'Cuisses et pilons grillés',
    description: 'Morceaux charnus marinés, grillés au charbon.',
    tempsPreparation: 50,
    coutPreparation: 18000,
    prixVente: 26000,
    categorie: 'Grillade',
    actif: true,
  },
  {
    id: '5',
    nom: 'Ailes de poulet miel-soja',
    description: 'Ailes marinées, caramélisées au miel et sauce soja.',
    tempsPreparation: 30,
    coutPreparation: 9000,
    prixVente: 15000,
    categorie: 'Entrée',
    actif: true,
  },
  {
    id: '6',
    nom: 'Blancs et aiguillettes de poulet',
    description: 'Viande maigre, idéale pour grillades ou plats diététiques.',
    tempsPreparation: 25,
    coutPreparation: 16000,
    prixVente: 24000,
    categorie: 'Plat',
    actif: true,
  },
  {
    id: '7',
    nom: 'Gésiers confits',
    description: 'Confit de gésiers dans la graisse de poulet, spécialité du Sud-Ouest.',
    tempsPreparation: 120,
    coutPreparation: 10000,
    prixVente: 18000,
    categorie: 'Traditionnel',
    actif: true,
  },
  {
    id: '8',
    nom: 'Foie de volaille sauté',
    description: 'Foie poêlé au vinaigre balsamique et oignons caramélisés.',
    tempsPreparation: 20,
    coutPreparation: 7000,
    prixVente: 14000,
    categorie: 'Entrée',
    actif: true,
  },

  // === 🍳 ŒUFS ET PRODUITS PONDEUSES ===
  {
    id: '9',
    nom: 'Œufs frais fermiers',
    description: 'Production d\'œufs frais locaux, vendus au plateau.',
    tempsPreparation: 1,
    coutPreparation: 4000,
    prixVente: 6000,
    categorie: 'Produit',
    actif: true,
  },
  {
    id: '10',
    nom: 'Omelette aux fines herbes',
    description: 'Œufs battus aux herbes fraîches et beurre.',
    tempsPreparation: 10,
    coutPreparation: 2000,
    prixVente: 5000,
    categorie: 'Entrée',
    actif: true,
  },
  {
    id: '11',
    nom: 'Œufs mimosa',
    description: 'Œufs durs farcis à la mayonnaise maison.',
    tempsPreparation: 15,
    coutPreparation: 3000,
    prixVente: 7000,
    categorie: 'Entrée',
    actif: true,
  },
  {
    id: '12',
    nom: 'Crème aux œufs vanillée',
    description: 'Dessert classique à base de lait, sucre et œufs.',
    tempsPreparation: 40,
    coutPreparation: 2500,
    prixVente: 6000,
    categorie: 'Dessert',
    actif: true,
  },

  // === 🌭 CHARCUTERIE ET TRANSFORMATIONS ===
  {
    id: '13',
    nom: 'Saucisses de poulet nature',
    description: 'Préparées à base de chair hachée et épices douces.',
    tempsPreparation: 45,
    coutPreparation: 12000,
    prixVente: 20000,
    categorie: 'Charcuterie',
    actif: true,
  },
  {
    id: '14',
    nom: 'Saucisses de poulet merguez',
    description: 'Version épicée au paprika et cumin.',
    tempsPreparation: 50,
    coutPreparation: 13000,
    prixVente: 21000,
    categorie: 'Charcuterie',
    actif: true,
  },
  {
    id: '15',
    nom: 'Nuggets croustillants maison',
    description: 'Morceaux de poulet panés à la panko.',
    tempsPreparation: 25,
    coutPreparation: 9000,
    prixVente: 15000,
    categorie: 'Produit',
    actif: true,
  },
  {
    id: '16',
    nom: 'Steak haché de poulet',
    description: 'Haché assaisonné, formé en galette tendre.',
    tempsPreparation: 20,
    coutPreparation: 12000,
    prixVente: 18000,
    categorie: 'Charcuterie',
    actif: true,
  },
  {
    id: '17',
    nom: 'Jambon de poulet',
    description: 'Pressé et cuit à la vapeur, découpé en tranches.',
    tempsPreparation: 90,
    coutPreparation: 16000,
    prixVente: 25000,
    categorie: 'Charcuterie',
    actif: true,
  },
  {
    id: '18',
    nom: 'Terrine de volaille',
    description: 'Préparation cuite au four à base de foie et chair de poulet.',
    tempsPreparation: 120,
    coutPreparation: 11000,
    prixVente: 20000,
    categorie: 'Charcuterie',
    actif: true,
  },
  {
    id: '19',
    nom: 'Brochettes de poulet marinées',
    description: 'Morceaux de poulet aux herbes et citron.',
    tempsPreparation: 25,
    coutPreparation: 11000,
    prixVente: 18000,
    categorie: 'Grillade',
    actif: true,
  },

  // === 🌍 RECETTES INTERNATIONALES ===
  {
    id: '20',
    nom: 'Poulet Tandoori',
    description: 'Mariné au yaourt et épices indiennes, cuit au four.',
    tempsPreparation: 45,
    coutPreparation: 15000,
    prixVente: 24000,
    categorie: 'International',
    actif: true,
  },
  {
    id: '21',
    nom: 'Poulet au curry thaï',
    description: 'Poulet au lait de coco, citronnelle et curry rouge.',
    tempsPreparation: 35,
    coutPreparation: 16000,
    prixVente: 24000,
    categorie: 'International',
    actif: true,
  },
  {
    id: '22',
    nom: 'Poulet Yassa (Sénégal)',
    description: 'Poulet mariné au citron et oignons caramélisés.',
    tempsPreparation: 60,
    coutPreparation: 13000,
    prixVente: 22000,
    categorie: 'International',
    actif: true,
  },
  {
    id: '23',
    nom: 'Poulet DG (Cameroun)',
    description: 'Poulet frit avec plantain et légumes sautés.',
    tempsPreparation: 60,
    coutPreparation: 17000,
    prixVente: 28000,
    categorie: 'International',
    actif: true,
  },
  {
    id: '24',
    nom: 'Poulet jerk (Jamaïque)',
    description: 'Marinade pimentée, grillé au feu de bois.',
    tempsPreparation: 40,
    coutPreparation: 15000,
    prixVente: 24000,
    categorie: 'Grillade',
    actif: true,
  },
  {
    id: '25',
    nom: 'Poulet au beurre (Inde)',
    description: 'Sauce tomate-crème, douce et parfumée.',
    tempsPreparation: 45,
    coutPreparation: 15000,
    prixVente: 24000,
    categorie: 'International',
    actif: true,
  },
  {
    id: '26',
    nom: 'Poulet teriyaki (Japon)',
    description: 'Glacé à la sauce soja sucrée-salée.',
    tempsPreparation: 30,
    coutPreparation: 13000,
    prixVente: 21000,
    categorie: 'International',
    actif: true,
  },
  {
    id: '27',
    nom: 'Pollo a la brasa (Pérou)',
    description: 'Poulet rôti mariné dans un mélange d\'épices péruviennes, accompagné de sauce verte.',
    tempsPreparation: 80,
    coutPreparation: 19000,
    prixVente: 30000,
    categorie: 'International',
    actif: true,
  },
  {
    id: '28',
    nom: 'Empanadas de poulet (Argentine)',
    description: 'Petits chaussons farcis au poulet, poivrons et oignons.',
    tempsPreparation: 35,
    coutPreparation: 8000,
    prixVente: 15000,
    categorie: 'International',
    actif: true,
  },
  {
    id: '29',
    nom: 'Arepas au poulet (Colombie)',
    description: 'Galettes de maïs garnies de poulet effiloché et avocat.',
    tempsPreparation: 30,
    coutPreparation: 10000,
    prixVente: 18000,
    categorie: 'International',
    actif: true,
  },
  {
    id: '30',
    nom: 'Tacos de poulet mexicains',
    description: 'Tortillas garnies de poulet mariné, pico de gallo et citron vert.',
    tempsPreparation: 25,
    coutPreparation: 9000,
    prixVente: 17000,
    categorie: 'International',
    actif: true,
  },
  {
    id: '31',
    nom: 'Poulet pimenté à la brésilienne',
    description: 'Poulet sauté avec sauce tomate, piment doux, coriandre et lait de coco.',
    tempsPreparation: 40,
    coutPreparation: 14000,
    prixVente: 23000,
    categorie: 'International',
    actif: true,
  },
  {
    id: '32',
    nom: 'Poulet Moambe (Congo)',
    description: 'Sauce à la pâte d\'arachide et huile de palme.',
    tempsPreparation: 70,
    coutPreparation: 16000,
    prixVente: 26000,
    categorie: 'International',
    actif: true,
  },
  {
    id: '33',
    nom: 'Poulet kedjenou (Côte d\'Ivoire)',
    description: 'Cuit à l\'étouffée dans pot en terre, épicé.',
    tempsPreparation: 90,
    coutPreparation: 17000,
    prixVente: 27000,
    categorie: 'International',
    actif: true,
  },
  {
    id: '34',
    nom: 'Poulet mafé',
    description: 'Sauce d\'arachide et légumes mijotés.',
    tempsPreparation: 80,
    coutPreparation: 16000,
    prixVente: 26000,
    categorie: 'International',
    actif: true,
  },
  {
    id: '35',
    nom: 'Poulet sauce gombo',
    description: 'Poulet mijoté dans sauce visqueuse de gombo.',
    tempsPreparation: 70,
    coutPreparation: 14000,
    prixVente: 22000,
    categorie: 'International',
    actif: true,
  },

  // === 🇫🇷 PLATS TRADITIONNELS ===
  {
    id: '36',
    nom: 'Poulet rôti à la Française',
    description: 'Au thym et citron, servi avec légumes.',
    tempsPreparation: 90,
    coutPreparation: 21000,
    prixVente: 31000,
    categorie: 'Traditionnel',
    actif: true,
  },
  {
    id: '37',
    nom: 'Poulet basquaise',
    description: 'Poulet mijoté à la tomate, poivrons et ail.',
    tempsPreparation: 60,
    coutPreparation: 15000,
    prixVente: 23000,
    categorie: 'Traditionnel',
    actif: true,
  },
  {
    id: '38',
    nom: 'Poulet à la crème et champignons',
    description: 'Sauce blanche riche et savoureuse.',
    tempsPreparation: 45,
    coutPreparation: 14000,
    prixVente: 21000,
    categorie: 'Traditionnel',
    actif: true,
  },
  {
    id: '39',
    nom: 'Poule au pot',
    description: 'Poule mijotée avec légumes du jardin.',
    tempsPreparation: 120,
    coutPreparation: 25000,
    prixVente: 34000,
    categorie: 'Plat',
    actif: true,
  },
  {
    id: '40',
    nom: 'Fricassée de volaille',
    description: 'Sauté de morceaux tendres en sauce blanche.',
    tempsPreparation: 60,
    coutPreparation: 15000,
    prixVente: 23000,
    categorie: 'Traditionnel',
    actif: true,
  },
  {
    id: '41',
    nom: 'Blanquette de poulet',
    description: 'Version légère de la blanquette classique.',
    tempsPreparation: 70,
    coutPreparation: 16000,
    prixVente: 25000,
    categorie: 'Traditionnel',
    actif: true,
  },

  // === 🔥 GRILLADES ET ASADO ===
  {
    id: '42',
    nom: 'Asado de poulet',
    description: 'Grillé lentement au feu de bois, sauce chimichurri.',
    tempsPreparation: 100,
    coutPreparation: 20000,
    prixVente: 30000,
    categorie: 'Grillade',
    actif: true,
  },
  {
    id: '43',
    nom: 'Poulet braisé',
    description: 'Grillé au charbon, mariné aux épices africaines.',
    tempsPreparation: 50,
    coutPreparation: 17000,
    prixVente: 25000,
    categorie: 'Grillade',
    actif: true,
  },
  {
    id: '44',
    nom: 'Poulet barbecue américain',
    description: 'Sauce BBQ maison, cuisson indirecte.',
    tempsPreparation: 60,
    coutPreparation: 16000,
    prixVente: 24000,
    categorie: 'Grillade',
    actif: true,
  },
  {
    id: '45',
    nom: 'Brochettes tex-mex',
    description: 'Poulet mariné au paprika fumé et maïs.',
    tempsPreparation: 30,
    coutPreparation: 12000,
    prixVente: 20000,
    categorie: 'Grillade',
    actif: true,
  },
  {
    id: '46',
    nom: 'Asado de cuisses de poulet',
    description: 'Marinées dans la bière, grillées croustillantes.',
    tempsPreparation: 80,
    coutPreparation: 18000,
    prixVente: 28000,
    categorie: 'Grillade',
    actif: true,
  },
  {
    id: '47',
    nom: 'Asado de poulet argentin',
    description: 'Poulet grillé lentement au feu de bois avec sauce chimichurri maison.',
    tempsPreparation: 90,
    coutPreparation: 20000,
    prixVente: 31000,
    categorie: 'Grillade',
    actif: true,
  },
  {
    id: '48',
    nom: 'Poulet churrasco brésilien',
    description: 'Brochettes de poulet marinées au citron vert, grillées à la flamme.',
    tempsPreparation: 60,
    coutPreparation: 18000,
    prixVente: 28000,
    categorie: 'Grillade',
    actif: true,
  },

  // === 🧆 PRODUITS TRAITÉS / STREET FOOD ===
  {
    id: '49',
    nom: 'Burger de poulet',
    description: 'Steak de poulet cajun, cheddar, sauce épicée.',
    tempsPreparation: 25,
    coutPreparation: 14000,
    prixVente: 22000,
    categorie: 'Produit',
    actif: true,
  },
  {
    id: '50',
    nom: 'Tacos de poulet',
    description: 'Tortilla garnie de poulet mariné et crudités.',
    tempsPreparation: 20,
    coutPreparation: 12000,
    prixVente: 20000,
    categorie: 'Produit',
    actif: true,
  },
  {
    id: '51',
    nom: 'Wraps poulet César',
    description: 'Poulet grillé, salade et sauce césar.',
    tempsPreparation: 15,
    coutPreparation: 10000,
    prixVente: 18000,
    categorie: 'Produit',
    actif: true,
  },
  {
    id: '52',
    nom: 'Panini poulet fromage',
    description: 'Poulet effiloché, mozzarella et tomates confites.',
    tempsPreparation: 15,
    coutPreparation: 9000,
    prixVente: 16000,
    categorie: 'Produit',
    actif: true,
  },
  {
    id: '53',
    nom: 'Kebab de poulet',
    description: 'Viande rôtie verticalement, servie dans pain pita.',
    tempsPreparation: 30,
    coutPreparation: 13000,
    prixVente: 21000,
    categorie: 'Produit',
    actif: true,
  },
  {
    id: '54',
    nom: 'Pizza poulet BBQ',
    description: 'Pizza maison à la sauce barbecue et mozzarella.',
    tempsPreparation: 35,
    coutPreparation: 14000,
    prixVente: 23000,
    categorie: 'Produit',
    actif: true,
  },

  // === 🍲 SOUPES ===
  {
    id: '55',
    nom: 'Soupe de poulet aux vermicelles',
    description: 'Bouillon clair au poulet, carottes et vermicelles, parfait en entrée.',
    tempsPreparation: 30,
    coutPreparation: 7000,
    prixVente: 12000,
    categorie: 'Soupe',
    actif: true,
  },
  {
    id: '56',
    nom: 'Soupe de maïs et poulet (Brésil)',
    description: 'Soupe crémeuse au maïs doux et effiloché de poulet.',
    tempsPreparation: 40,
    coutPreparation: 10000,
    prixVente: 17000,
    categorie: 'Soupe',
    actif: true,
  },
  {
    id: '57',
    nom: 'Ajiaco colombiano',
    description: 'Soupe traditionnelle colombienne au poulet, maïs et pommes de terre.',
    tempsPreparation: 60,
    coutPreparation: 12000,
    prixVente: 20000,
    categorie: 'Soupe',
    actif: true,
  },

  // === 🍮 DESSERTS ===
  {
    id: '58',
    nom: 'Flan aux œufs',
    description: 'Dessert classique à base d\'œufs, lait et sucre.',
    tempsPreparation: 45,
    coutPreparation: 2500,
    prixVente: 6000,
    categorie: 'Dessert',
    actif: true,
  },
  {
    id: '59',
    nom: 'Gâteau aux œufs battus',
    description: 'Recette simple et moelleuse, parfumée à la vanille.',
    tempsPreparation: 40,
    coutPreparation: 3000,
    prixVente: 8000,
    categorie: 'Dessert',
    actif: true,
  },
  {
    id: '60',
    nom: 'Crêpes aux œufs frais',
    description: 'Pâte fine et dorée, garnie de confiture ou miel.',
    tempsPreparation: 20,
    coutPreparation: 2000,
    prixVente: 5000,
    categorie: 'Dessert',
    actif: true,
  },
];

export default recettesExemple;